name: Node CI

on: 
  push:
    branches:
       - master # execute `deploy job` on push@gh-pages
  pull_request:
    branches: 
      - dev    # execute `test job` on pull_request@master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: test pull_request
        uses: actions/checkout@v1
        if: github.event_name == 'pull_request'        
        with:
          node-version: '12.x'
          run: |
            echo "Installing dependencies"
            yarn global add @vue/cli
            yarn install
            
            echo "Testing code with lint"
            yarn lint 
            
            echo "Testing production"
            yarn -s serve
            
            echo "Producing SPA in dist directory for production"
            yarn build
            echo "Finished testing"
 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: deployment to gh-pages
        uses: actions/checkout@v1
        if: github.event_name == 'push'
        with:
          node-version: '12.x'
          run: |
            echo "Installing dependencies"
            yarn global add @vue/cli
            yarn install
            
            echo "Testing codes with lint"
            yarn lint
            
            echo "Testing production"
            yarn -s serve
            
            echo "Producing SPA in dist directory for production"
            yarn build
            
            echo "Removing unwanted files"
            rm -rf package.json .gitignore vue.config.js babel.config.js public/ src/ yarn-error.log deploy.sh LICENSE README.md yarn.lock
            
            echo "Moving dist/ to root directory and removing dist/ dir"
            mv dist/* . && rmdir dist/
